package com.liljeson.mattias.fries.interpretator;

public class RDITestData {
	static final String[] TST0 = {
			"###PROGRAM###",
			"    1",
			"##BLOCK##",
			"  0 -1  0  0    3",
			"#DEKLARATIONER#",
			"#KOD#",
			"    2    7    Line#",
			"    3    7    Line#",
			"    2    1    end",
			"##BLOCKSLUT##",
			"###PROGRAMSLUT###" };

	static final String[] TST1 = {
			"###PROGRAM###",
			"    1",
			"##BLOCK##",
			"  0 -1  1  1   10",
			"#DEKLARATIONER#",
			"   19    1    0    0    0    0    0  **   #   I",
			"#KOD#",
			"    2    7    Line#",
			"    3    7    Line#",
			"    4    7    Line#",
			"    5    7    Line#",
			"   19    1    I",
			"    6    5    :=",
			"    2    2    2",
			"    1    5    ;",
			"    6    7    Line#",
			"    2    1    end",
			"##BLOCKSLUT##",
			"###PROGRAMSLUT###",
	};

	static final String[] TST2 = {
			"###PROGRAM###",
			"    1",
			"##BLOCK##",
			"  0 -1  2  2   22",
			"#DEKLARATIONER#",
			"   19    1    0    0    0    0    0  **   #   I",
			"   20    1    0    0    0    0    1  **   #   K",
			"#KOD#",
			"    2    7    Line#",
			"    3    7    Line#",
			"    4    7    Line#",
			"    5    7    Line#",
			"   19    1    I",
			"    6    5    :=",
			"    2    2    2",
			"    1    5    ;",
			"# BREAKPOINT",
			"    6    7    Line#",
			"   20    1    K",
			"    6    5    :=",
			"    3    2    3",
			"    1    5    ;",
			"# BREAKPOINT",
			"    7    7    Line#",
			"   19    1    I",
			"    6    5    :=",
			"   19    1    I",
			"   13    5    +",
			"   20    1    K",
			"    1    5    ;",
			"    8    7    Line#",
			"    2    1    end",
			"##BLOCKSLUT##",
			"###PROGRAMSLUT###",
	};

	static final String[] TST3 = {
			"###PROGRAM###",
			"    1",
			"##BLOCK##",
			"  0 -1  2  2   27",
			"#DEKLARATIONER#",
			"   19    1    0    0    0    0    0  **   #   I",
			"   20    1    0    0    0    0    1  **   #   K",
			"#KOD#",
			"    2    7    Line#",
			"    3    7    Line#",
			"    4    7    Line#",
			"    5    7    Line#",
			"    6    7    Line#",
			"   19    1    I",
			"    6    5    :=",
			"    2    2    2",
			"    1    5    ;",
			"    7    7    Line#",
			"   20    1    K",
			"    6    5    :=",
			"    3    2    3",
			"    1    5    ;",
			"# BREAKPOINT",
			"    8    7    Line#",
			"   19    1    I",
			"    6    5    :=",
			"   19    1    I",
			"   13    5    +",
			"   20    1    K",
			"   15    5    *",
			"   19    1    I",
			"   14    5    -",
			"   20    1    K",
			"    1    5    ;",
			"    9    7    Line#",
			"    2    1    end",
			"##BLOCKSLUT##",
			"###PROGRAMSLUT###"
	};

	static final String[] TST4 = {
			"###PROGRAM###",
			"    2",
			"##BLOCK##",
			"  0 -1  2  2   25",
			"#DEKLARATIONER#",
			"   19    1    0    0    0    0    0  **   #   I",
			"   20    1    0    0    0    0    1  **   #   K",
			"#KOD#",
			"    2    7    Line#",
			"    3    7    Line#",
			"    4    7    Line#",
			"    5    7    Line#",
			"   19    1    I",
			"    6    5    :=",
			"    2    2    2",
			"    1    5    ;",
			"    6    7    Line#",
			"   20    1    K",
			"    6    5    :=",
			"    3    2    3",
			"    1    5    ;",
			"    7    7    Line#",
			"    8    7    Line#",
			"    1   10    Callblock",
			"   12    7    Line#",
			"   19    1    I",
			"    6    5    :=",
			"   20    1    K",
			"   15    5    *",
			"   19    1    I",
			"    1    5    ;",
			"   13    7    Line#",
			"    2    1    end",
			"##BLOCKSLUT##",
			"##BLOCK##",
			"  1  0  1  1   14",
			"#DEKLARATIONER#",
			"   19    1    0    0    0    0    0  **   #   I",
			"#KOD#",
			"    9    7    Line#",
			"   19    1    I",
			"    6    5    :=",
			"    4    2    4",
			"    1    5    ;",
			"   10    7    Line#",
			"   20    1    K",
			"    6    5    :=",
			"   19    1    I",
			"   13    5    +",
			"   20    1    K",
			"    1    5    ;",
			"   11    7    Line#",
			"    2    1    end",
			"##BLOCKSLUT##",
			"###PROGRAMSLUT###",
	};

	static final String[] TST5 = {
			"###PROGRAM###",
			"    2",
			"##BLOCK##",
			"  0 -1  1  2   27",
			"#DEKLARATIONER#",
			"   19    1    2    1    1    0    0  **   #   F",
			"   21    1    0    0    0    0    0  **   #   I",
			"#KOD#",
			"    2    7    Line#",
			"    3    7    Line#",
			"    4    7    Line#",
			"    5    7    Line#",
			"   21    1    I",
			"    6    5    :=",
			"    3    2    3",
			"    1    5    ;",
			"    6    7    Line#",
			"   21    1    I",
			"    6    5    :=",
			"   21    1    I",
			"   13    5    +",
			"   19    1    F",
			"    2    5    (",
			"    2    2    2",
			"    3    5    )",
			"   15    5    *",
			"   21    1    I",
			"   13    5    +",
			"   19    1    F",
			"    2    5    (",
			"   21    1    I",
			"    3    5    )",
			"    1    5    ;",
			"    7    7    Line#",
			"    2    1    end",
			"##BLOCKSLUT##",
			"##BLOCK##",
			"  1  0  2  2    6",
			"#DEKLARATIONER#",
			"   19    1    3    0    0    0    0  **   #   F",
			"   20    1    0    0    0    0    1  **   #   X",
			"#KOD#",
			"   19    1    F",
			"    6    5    :=",
			"   20    1    X",
			"   13    5    +",
			"    1    2    1",
			"    1    5    ;",
			"##BLOCKSLUT##",
			"###PROGRAMSLUT###"
	};

	static final String[] TST6 = {
			"###PROGRAM###",
			"    2",
			"##BLOCK##",
			"  0 -1  1  2   27",
			"#DEKLARATIONER#",
			"   19    1    2    1    1    0    0  **   #   F",
			"   21    1    0    0    0    0    0  **   #   I",
			"#KOD#",
			"    2    7    Line#",
			"    3    7    Line#",
			"    7    7    Line#",
			"    8    7    Line#",
			"   21    1    I",
			"    6    5    :=",
			"    3    2    3",
			"    1    5    ;",
			"    9    7    Line#",
			"   21    1    I",
			"    6    5    :=",
			"   21    1    I",
			"   13    5    +",
			"   19    1    F",
			"    2    5    (",
			"    2    2    2",
			"    3    5    )",
			"   15    5    *",
			"   21    1    I",
			"   13    5    +",
			"   19    1    F",
			"    2    5    (",
			"   21    1    I",
			"    3    5    )",
			"    1    5    ;",
			"   10    7    Line#",
			"    2    1    end",
			"##BLOCKSLUT##",
			"##BLOCK##",
			"  1  0  2  2   24",
			"#DEKLARATIONER#",
			"   19    1    3    0    0    0    0  **   #   F",
			"   20    1    0    0    0    0    1  **   #   X",
			"#KOD#",
			"    4    7    Line#",
			"    5    7    Line#",
			"   10    1    if",
			"   20    1    X",
			"   11    5    >",
			"    0    2    0",
			"   11    1    then",
			"   19    1    F",
			"    6    5    :=",
			"   20    1    X",
			"   13    5    +",
			"   19    1    F",
			"    2    5    (",
			"   20    1    X",
			"   14    5    -",
			"    1    2    1",
			"    3    5    )",
			"   12    1    else",
			"   19    1    F",
			"    6    5    :=",
			"    0    2    0",
			"    1    5    ;",
			"    6    7    Line#",
			"    2    1    end",
			"##BLOCKSLUT##",
			"###PROGRAMSLUT###"
	};

	static final String[] TST7 = {
			"###PROGRAM###",
			"    4",
			"##BLOCK##",
			"  0 -1  1  2   30",
			"#DEKLARATIONER#",
			"   19    1    2    1    1    0    0  **   #   F",
			"   22    1    0    0    0    0    0  **   #   I",
			"#KOD#",
			"    2    7    Line#",
			"    3    7    Line#",
			"   13    7    Line#",
			"   14    7    Line#",
			"   22    1    I",
			"    6    5    :=",
			"    3    2    3",
			"    1    5    ;",
			"   15    7    Line#",
			"   16    7    Line#",
			"    3   10    Callblock",
			"   20    7    Line#",
			"   22    1    I",
			"    6    5    :=",
			"   22    1    I",
			"   13    5    +",
			"   19    1    F",
			"    2    5    (",
			"    2    2    2",
			"    3    5    )",
			"   15    5    *",
			"   22    1    I",
			"   13    5    +",
			"   19    1    F",
			"    2    5    (",
			"   22    1    I",
			"    3    5    )",
			"    1    5    ;",
			"   21    7    Line#",
			"    2    1    end",
			"##BLOCKSLUT##",
			"##BLOCK##",
			"  1  0  2  2   24",
			"#DEKLARATIONER#",
			"   19    1    3    0    0    0    0  **   #   F",
			"   20    1    0    0    0    0    1  **   #   X",
			"#KOD#",
			"    4    7    Line#",
			"    5    7    Line#",
			"   10    1    if",
			"   20    1    X",
			"   11    5    >",
			"    0    2    0",
			"   11    1    then",
			"   19    1    F",
			"    6    5    :=",
			"   20    1    X",
			"   13    5    +",
			"   19    1    F",
			"    2    5    (",
			"   20    1    X",
			"   14    5    -",
			"    1    2    1",
			"    3    5    )",
			"    6    7    Line#",
			"   12    1    else",
			"    7    7    Line#",
			"    8    7    Line#",
			"    2   10    Callblock",
			"   12    7    Line#",
			"    2    1    end",
			"##BLOCKSLUT##",
			"##BLOCK##",
			"  2  1  1  1   14",
			"#DEKLARATIONER#",
			"   21    1    0    0    0    0    0  **   #   K",
			"#KOD#",
			"    9    7    Line#",
			"   21    1    K",
			"    6    5    :=",
			"   22    1    I",
			"   14    5    -",
			"    1    2    1",
			"    1    5    ;",
			"   10    7    Line#",
			"   19    1    F",
			"    6    5    :=",
			"   21    1    K",
			"    1    5    ;",
			"   11    7    Line#",
			"    2    1    end",
			"##BLOCKSLUT##",
			"##BLOCK##",
			"  3  0  1  1   21",
			"#DEKLARATIONER#",
			"   21    1    0    0    0    0    0  **   #   K",
			"#KOD#",
			"   17    7    Line#",
			"   21    1    K",
			"    6    5    :=",
			"   19    1    F",
			"    2    5    (",
			"   22    1    I",
			"   13    5    +",
			"    1    2    1",
			"    3    5    )",
			"   15    5    *",
			"    2    2    2",
			"    1    5    ;",
			"   18    7    Line#",
			"   22    1    I",
			"    6    5    :=",
			"   21    1    K",
			"   13    5    +",
			"    1    2    1",
			"    1    5    ;",
			"   19    7    Line#",
			"    2    1    end",
			"##BLOCKSLUT##",
			"###PROGRAMSLUT###"
	};

	static final String[] TST8 = {
			"###PROGRAM###",
			"    1",
			"##BLOCK##",
			"  0 -1  2  2   48",
			"#DEKLARATIONER#",
			"   19    1    0    0    0    0    0  **   #   I",
			"   20    1    1    1    0    0    1  **    1  2  6  A",
			"#KOD#",
			"    2    7    Line#",
			"    3    7    Line#",
			"    4    7    Line#",
			"   19    1    I",
			"    6    5    :=",
			"    4    2    4",
			"    1    5    ;",
			"    5    7    Line#",
			"   20    1    A",
			"    2    5    (",
			"    3    2    3",
			"    3    5    )",
			"    6    5    :=",
			"    5    2    5",
			"    1    5    ;",
			"    6    7    Line#",
			"   20    1    A",
			"    2    5    (",
			"   19    1    I",
			"    3    5    )",
			"    6    5    :=",
			"   19    1    I",
			"   13    5    +",
			"   20    1    A",
			"    2    5    (",
			"    3    2    3",
			"    3    5    )",
			"    1    5    ;",
			"    7    7    Line#",
			"   20    1    A",
			"    2    5    (",
			"   19    1    I",
			"   13    5    +",
			"    1    2    1",
			"    3    5    )",
			"    6    5    :=",
			"   20    1    A",
			"    2    5    (",
			"    4    2    4",
			"    3    5    )",
			"   15    5    *",
			"   20    1    A",
			"    2    5    (",
			"    3    2    3",
			"    3    5    )",
			"    1    5    ;",
			"    8    7    Line#",
			"    2    1    end",
			"##BLOCKSLUT##",
			"###PROGRAMSLUT###"
	};

	static final String[] TST9 = {
			"###PROGRAM###",
			"    1",
			"##BLOCK##",
			"  0 -1  1  1   44",
			"#DEKLARATIONER#",
			"   19    1    0    0    0    0    0  **   #   I",
			"#KOD#",
			"    2    7    Line#",
			"    3    7    Line#",
			"   19    1    I",
			"    6    5    :=",
			"    5    2    5",
			"    1    5    ;",
			"    4    7    Line#",
			"   20    1    write",
			"    2    5    (",
			"   19    1    I",
			"    3    5    )",
			"    1    5    ;",
			"    5    7    Line#",
			"   21    1    writln",
			"    1    5    ;",
			"    6    7    Line#",
			"   19    1    I",
			"    6    5    :=",
			"   22    1    readint",
			"    1    5    ;",
			"    7    7    Line#",
			"   20    1    write",
			"    2    5    (",
			"   19    1    I",
			"    3    5    )",
			"    1    5    ;",
			"    8    7    Line#",
			"   21    1    writln",
			"    1    5    ;",
			"    9    7    Line#",
			"   20    1    write",
			"    2    5    (",
			"   19    1    I",
			"   13    5    +",
			"   22    1    readint",
			"   14    5    -",
			"    2    2    2",
			"    3    5    )",
			"    1    5    ;",
			"   10    7    Line#",
			"   21    1    writln",
			"    1    5    ;",
			"   11    7    Line#",
			"    2    1    end",
			"##BLOCKSLUT##",
			"###PROGRAMSLUT###"
	};

	static final String[] FEL = {

			};
}
